### ISSUE TITLE
Why is use_lidar set true for detr3d

### ISSUE THREAD

**Issue by shubham-gupta-iitr** [WangYueFt/detr3d#1]
Hi,
Thanks for this amazing work. I was going through the code and saw that you've kept `use_lidar=true` here for DETR3D
https://github.com/WangYueFt/detr3d/blob/main/projects/configs/detr3d/detr3d_res101_gridmask.py#L23
I was expecting since its an image-based method, it should be kept false, and also the file should look similar to-
https://github.com/open-mmlab/mmdetection3d/blob/master/configs/_base_/datasets/nus-mono3d.py

Thanks

**Comment by WangYueFt** [comment]
Sorry that was a typo and shouldn't affect the results. I've just fixed it.
