### ISSUE TITLE
Question about the time complexity of Object DGCNN

### ISSUE THREAD

**Issue by BoomSky0416** [WangYueFt/detr3d#10]
![image](https://user-images.githubusercontent.com/57380777/145332320-e6979ad6-7bd8-418c-88ab-9efba7e45f8e.png)
From your result in the paper, fps of your model is smaller than other models with nms. And from my understanding, bigger fps means better performance, but you said your model is more efficient. Could you explain it why your model is more efficient with smaller fps?

**Comment by WangYueFt** [comment]
Sorry this was a mistake. This time complexity was measured without taking NMS into account (PointPillars, Pillar-OD, CenterPoint didn't include the NMS in the complexity). We will fix the results soon.
