### ISSUE TITLE
Maybe a typo in detr3d_vovnet_gridmask_det_final_trainval_cbgs's config

### ISSUE THREAD

**Issue by wchstrife** [WangYueFt/detr3d#13]
Hi,
When I did the experiment on NuScenesDataset, I found that an error was reported in the configuration file [detr3d_vovnet_gridmask_det_final_trainval_cbgs.py](https://github.com/WangYueFt/detr3d/blob/main/projects/configs/detr3d/detr3d_vovnet_gridmask_det_final_trainval_cbgs.py) and there was no such file in the NuScenesDataset. `ann_file=data_root + 'nuscenes_infos_trainval.pkl'`(line 192), maybe it should be `ann_file=data_root + 'nuscenes_infos_train.pkl'`?

**Comment by a1600012888** [comment]
Thanks for pointing this out!  It is a typo for training models on training split and evaluate under validation split. 

the trainval split can be used to train model when you want to submit models to the test track(the nuscenes leaderboard: https://www.nuscenes.org/object-detection?externalData=all&mapData=all&modalities=Camera)
