### ISSUE TITLE
About external data on the list of nuscenes

### ISSUE THREAD

**Issue by SelinaChe** [WangYueFt/detr3d#14]
Hi, Could you please tell me what is the external data you used (showing on the rankings of nuscenes)? Public or private datasets?
![image](https://user-images.githubusercontent.com/23215919/149929463-1213af8a-1798-4987-a25e-40981c2563ef.png)

**Comment by a1600012888** [comment]
Hi, 
This Extern data as "yes" denotes that our test track submitted models are pretrained on external dataset. 

We use the pretrained model from DD3D models, and DD3D models are pretrained on their private dataset. see detail in https://github.com/tri-ml/dd3d

**Comment by SelinaChe** [comment]
Thanks ^^
