### ISSUE TITLE
the detail about mmdet3d version?

### ISSUE THREAD

**Issue by jonyzhang2023** [WangYueFt/detr3d#18]
hi
thx for the great job , can someone tell me the detail rely version about this repo?
i try to follow the mmdetection3d but all failed.

pytorch==1.7.0 torchvision==0.8.0 torchaudio==0.7.0 cudatoolkit=11.0 
mmcv=1.4.0 mmsegmentation=0.14.1  mmdet=2.14.0
not works

**Comment by zituka** [comment]
i just fine the log.

**Comment by jonyzhang2023** [comment]
i just find the log, it has details.
