### ISSUE TITLE
The result of detr3d

### ISSUE THREAD

**Issue by feifei-Liu** [WangYueFt/detr3d#2]
Hello, thank you very much for your work. We try to reproduce [detr3d](https://github.com/WangYueFt/detr3d/blob/main/projects/configs/detr3d/detr3d_res101_gridmask.py), but we can only get MAP=0.3233. Here is our training [log](https://drive.google.com/file/d/1nwe_sRf-KzlTBo5cOJ673gzhWJJp-xVU/view?usp=sharing).
The result of the validation set is at the end of the file.  Thank you very much!

**Comment by ZJUwangdaiyin** [comment]
Hi, did you reproduce the results later?

**Comment by ZJUwangdaiyin** [comment]
> Hello, thank you very much for your work. We try to reproduce [detr3d](https://github.com/WangYueFt/detr3d/blob/main/projects/configs/detr3d/detr3d_res101_gridmask.py), but we can only get MAP=0.3233. Here is our training [log](https://drive.google.com/file/d/1nwe_sRf-KzlTBo5cOJ673gzhWJJp-xVU/view?usp=sharing). The result of the validation set is at the end of the file. Thank you very much!
Hi, did you reproduce the results later?

**Comment by ZJUwangdaiyin** [comment]
> Hello, thank you very much for your work. We try to reproduce [detr3d](https://github.com/WangYueFt/detr3d/blob/main/projects/configs/detr3d/detr3d_res101_gridmask.py), but we can only get MAP=0.3233. Here is our training [log](https://drive.google.com/file/d/1nwe_sRf-KzlTBo5cOJ673gzhWJJp-xVU/view?usp=sharing). The result of the validation set is at the end of the file. Thank you very much!

Hi, did you reproduce the results later?
