### ISSUE TITLE
feature_sampling problem

### ISSUE THREAD

**Issue by yvaine** [WangYueFt/detr3d#27]
hi, thank you for your work, i have a problem in feature_sampling function,  the following code
`reference_points_cam = (reference_points_cam - 0.5) * 2`
why need multiply 2?
Thank you for reply!

**Comment by zhanglazhuan** [comment]
for torch grid_sampler, the value should be [-1, 1]
this code is trans [0, 1] to [-1, 1], I think so

**Comment by yvaine** [comment]
> for torch grid_sampler, the value should be [-1, 1] this code is trans [0, 1] to [-1, 1], I think so

Thank you~ That's correct.

**Comment by a1600012888** [comment]
Thanks, your understanding is correct.
