### ISSUE TITLE
How to visualize the results of predictions on images? 

### ISSUE THREAD

**Issue by kaixinbear** [WangYueFt/detr3d#28]
I have read the mmdet3d doc and run the visualize_results.py script.But I can only get ***.obj file.
How can I visualize results on images?

**Comment by a1600012888** [comment]
Hi. 
Below I provide new code based the official implementation of NuScenesExplorer.
https://drive.google.com/file/d/1rcrATkd2wgUMeaaP8tHBz0S6hKe-zkhc/view?usp=sharing

The function render_sample_pred in line 344 can render predictions from any detectors, with the similar figures from DETR3D(Lidar bev or any camera. With or without maps)
A partial example is showed in _test_pred()
You can use this code to perform visualization for results json file from any detectors.

See: https://github.com/WangYueFt/detr3d/issues/20

**Comment by kaixinbear** [comment]
Thank you very much!
