### ISSUE TITLE
Any attempts on kitti?

### ISSUE THREAD

**Issue by Muyiyunzi** [WangYueFt/detr3d#3]
Hello!
First of all, thanks so much for your great efforts, it's really amazing to have DETR3D here! I see that you didn't report any results on KITTI-object in your paper since nuScenes provides more sequential data that benefits the use of transformer-ish architecture. So I would like to ask whether you ran some test on KITTI dataset, or if someone else has reproduced the method on KITTI, which would be really appreciated.
Kind regards.

**Comment by a1600012888** [comment]
Hi, 
we didn't run experiments on KITTI dataset.
