### ISSUE TITLE
Car detection performance of checkpoint on nuscenes mini is poor

### ISSUE THREAD

**Issue by hrz2000** [WangYueFt/detr3d#58]
I use this checkpoint file to test on the nuscenes mini verification set
![image](https://user-images.githubusercontent.com/79900945/207379112-d6754b32-c8c7-4a2c-bbfb-1eac4e2a7b4d.png)
The evaluation indicators are as follows: 
![image](https://user-images.githubusercontent.com/79900945/207379293-022d1142-4008-4b26-9807-a42a7f0ea371.png)
![image](https://user-images.githubusercontent.com/79900945/207379702-de79a030-6793-4aa9-9e86-5c6798bd5179.png)

It seems that the car detection is much worse than the pedestrian detection. Is this a normal phenomenon and what may be the cause.

In the visualized figure, blue indicates that the confidence level in the prediction is greater than 0.2, and green indicates the ground truth. Please ignore the red Chinese mark in the figure~

**Comment by niangea** [comment]
请问你是怎么下载数据集的呢

**Comment by hrz2000** [comment]
抱歉，之前已经找到了原因，没有及时关闭issue
是因为我把多相机改成了只使用1个相机的原因，参数对应存在问题，非常感谢您的帮助。
